export const events = [
  {
    id: "event-1",
    title: "Kariyer Günleri 2026",
    category: "Seminer",
    date: "12-10-2026",
    time: "14:00",
    location: "A Blok Konferans Salonu",
    capacity: 100,
    description: "Mezunlarla kariyer söyleşileri ve şirket standları.",
  },
  {
    id: "event-2",
    title: "Robotik Atölyesi",
    category: "Atölye",
    date: "20-10-2026",
    time: "10:00",
    location: "Bilgisayar Laboratuvarı 2",
    capacity: 20,
    description: "Arduino ile çizgi izleyen robot yapımı, başlangıç seviyesi.",
  },
  {
    id: "event-3",
    title: "Siber Güvenlik Söyleşisi",
    category: "Söyleşi",
    date: "27-10-2026",
    time: "13:00",
    location: "B Blok Amfi 1",
    capacity: 50,
    description: "Sektörden bir uzmanla güvenlik kariyeri üzerine sohbet.",
  },
  {
    id: "event-4",
    title: "Web Tasarım Atölyesi",
    category: "Atölye",
    date: "03-11-2026",
    time: "15:00",
    location: "Bilgisayar Laboratuvarı 1",
    capacity: 30,
    description: "HTML ve CSS ile ilk kişisel sayfanı yap.",
  },
  {
    id: "event-5",
    title: "Yapay Zekaya Giriş Semineri",
    category: "Seminer",
    date: "10-11-2026",
    time: "11:00",
    location: "B Blok Amfi 2",
    capacity: 80,
    description: "Günlük hayattaki uygulamalarıyla makine öğrenmesine giriş.",
  },
  {
    id: "event-6",
    title: "Açık Kaynak Söyleşisi",
    category: "Söyleşi",
    date: "17-11-2026",
    time: "14:00",
    location: "A Blok Konferans Salonu",
    capacity: 60,
    description: "Açık kaynak projelere katkı vermeye nasıl başlanır?",
  },
];